[package]
name = "screen-13-imgui"
version = "0.1.0"
authors = ["John Wells <john@attackgoat.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
bytemuck = "1.24"
imgui = "0.12"
imgui-winit-support = "0.13"
inline-spirv = "0.2"
screen-13 = { path = "../.." }
